README.md, src/JLD2.jl, src/loadsave.jl, test/loadsave.jl, test/runtests.jl
=> Don't extend FileIO's load and save

src/data.jl, test/consistency.jl, test/recon.jl
Also fix some bugs found in the process.
=> Improve code coverage

src/data.jl
ref https://github.com/simonster/JLD2.jl/pull/28/files#r132098827
=> use the merge commit as VERSION cutoff for struct_type expr head

src/loadsave.jl, test/loadsave.jl
=> Make `load` return flattened group structure

.travis.yml, REQUIRE, appveyor.yml, src/JLD2.jl, src/data.jl, src/dataio.jl, src/datasets.jl, src/mmapio.jl, test/append.jl, test/consistency.jl, test/groups.jl, test/internal.jl, test/loadsave.jl, test/lookup3.jl, test/recon.jl, test/runtests.jl, test/rw.jl
Fixes many deprecation warnings in addition to breakages. Tests pass on 0.6 and 0.7 locally.
=> Fix on 0.7

src/JLD2.jl, src/data.jl, src/dataspaces.jl, src/mmapio.jl, test/customserialization.jl
Closes #49. (I ran Deprecations.jl locally to produce this)
=> Fix deprecation warnings on 0.7

.travis.yml, appveyor.yml, src/JLD2.jl, src/bufferedio.jl, src/data.jl, src/dataio.jl, src/datasets.jl, src/dataspaces.jl, src/datatypes.jl, src/global_heaps.jl, src/loadsave.jl, src/misc.jl, src/mmapio.jl, test/customserialization.jl, test/internal.jl, test/lookup3.jl, test/runtests.jl, test/rw.jl
Changes from #76 are included here with authorship preserved.
Fixes #75
Fixes #74
Closes #76
=> Fixes and updates for Julia 0.7

src/data.jl
this threw an error in Julia 1.0
=> eval -> Core.eval

src/data.jl, test/internal.jl
Addresses #88. All tests pass after rebasing onto master.
=> Make typename always include the module part II (THIS TIME, IT'S PERSONAL)

test/A.jl, test/B.jl, test/modules.jl, test/runtests.jl
I started work on a bug report, then realised the bug had been fixed since the last release.  However, it strikes me as the kind of bug that's likely to regress.
=> add regression test for JuliaIO#134

.gitignore, .travis.yml, Project.toml, src/JLD2.jl, src/data.jl, src/stdlib.jl, test/append.jl, test/consistency.jl, test/customserialization.jl, test/groups.jl, test/isreconstructed.jl, test/loadsave.jl, test/modules-nested.jl, test/modules.jl, test/recon.jl, test/runtests.jl, test/rw.jl
Fixes #112 
Fixes #149 
This pull request makes the following changes:
- Works harder to resolve the scope of types (building upon the work of #149)
- Adds the example described in #149 as a test
- Adds some test-only dependencies to make the example work
- Starts testing on Julia 1.2
=> Work harder to resolve the scope when trying to resolve types - fixes several bugs

Project.toml, test/functions_and_calls.jl
Adds regression tests for the functionality of https://github.com/JuliaIO/JLD2.jl/issues/122 and https://github.com/JuliaIO/JLD2.jl/issues/128
Closes #122 
Closes #128
=> Add regression tests for call overloading and functions

Project.toml
You may want to use [`CompatHelper.jl`](https://github.com/bcbi/CompatHelper.jl)
=> Allow installing CodecZlib v0.7

Project.toml, src/data.jl
Should be compatible with all versions.
=> fix #195, struct_type failure on 1.5

test/loadsave.jl
This test verifies that issue #131  has been solved
( corruption when saving `Vector{Union{T,Missing}}`)
... and likely also issue #171  and issue #131 
- Jonas
closes #171
closes #131
=> Test for issue #131

src/mmapio.jl, test/loadsave.jl
=> Fix segmentation fault when reading a file that doesn't exist

appveyor.yml, test/modules-nested.jl
This brings the appveyor.yml up to speed and fixes the tests for windows.
=> fix tests on windows

src/mmapio.jl
The specification for `MMAP` says:
> Note that references beyond the end of the object do not extend the object as the new end cannot be determined precisely by most virtual memory hardware. Instead, the size can be directly manipulated by ftruncate().
[https://pubs.opengroup.org/onlinepubs/009695399/functions/mmap.html](https://pubs.opengroup.org/onlinepubs/009695399/functions/mmap.html)
This seems to be the problem with `pwrite`. It works on most systems but not on NFS.
Instead it is recommended to use `ftruncate`.
Anyone reading this, please compare the speed of writing files  with `JLD2v0.2.0` and this PR.
And if you have encountered #55 before please check whether it is fixed using this PR.
closes #55   !!
closes #1
=> use ftruncate instead of pwrite

Project.toml, src/groups.jl, test/groups.jl
closes #278
New behaviour is to error less. Just return false if the path is not valid.
=> better haskey method

.github/workflows/ci.yml, test/loadsave.jl
This PR in FileIO broke an `@test_throws` test
https://github.com/JuliaIO/FileIO.jl/pull/305
=> change testthrows exception

Project.toml, docs/src/index.md, src/JLD2.jl, src/loadsave.jl, test/loadsave.jl
This pull request closes Issue #210
=> Adds load_object and save_object functionality

Project.toml, src/JLD2.jl, src/fileio.jl
I realized, it's stupid to not have a proper loading / saving function by default
=> add FileIO dependency again

src/groups.jl, test/groups.jl
=> fix corner case of repeated appending to groups

src/JLD2.jl, src/compression.jl, src/datasets.jl, test/compression.jl
=> Better error messages for invalid compressor arguments

src/data/reconstructing_datatypes.jl, test/loadsave.jl
=> fix for #329

src/inlineunion.jl, test/inlineunion.jl
=> test for 348

CHANGELOG.md, Project.toml, src/data/reconstructing_datatypes.jl, test/loadsave.jl
=> fix reconstruction of partially init structs

docs/src/advanced.md, docs/src/index.md, docs/src/internals.md, src/JLD2.jl, src/loadsave.jl
closes #115 
closes #311
closes #303
closes #277 
closes #255
closes #236
closes #226
=> Various things such as docs 

README.md
I would consider making compress enabled the default behavior.
=> make compress doc more visible

CHANGELOG.md, Project.toml, README.md, src/data/custom_serialization.jl, src/data/reconstructing_datatypes.jl, src/data/writing_datatypes.jl, test/loadsave.jl
=> identity preservation for custom serialized structs

src/data/number_types.jl, src/data/reconstructing_datatypes.jl, src/data/type_defs.jl, src/data/writing_datatypes.jl
Closes https://github.com/JuliaIO/JLD2.jl/issues/428.
=> Do not access .size field in DataType

src/object_headers.jl
=> use UInt64 for chunk_dimensions

CHANGELOG.md, benchmark/benchmark.jl, src/attributes.jl, src/compression.jl, src/data/custom_serialization.jl, src/data/writing_datatypes.jl, src/inlineunion.jl, src/loadsave.jl, src/object_headers.jl, src/superblock.jl
Corrects some typos in the repository.
=> Correct some typos

src/compression.jl, src/groups.jl, src/misc.jl
- improve `to_uint64`
- fix failure to const-prop in error message
- improve type stability in show_group
=> A few minor perforamnce fixes

src/data/specialcased_types.jl
=> bignum fix

docs/src/customserialization.md, src/data/specialcased_types.jl, src/datasets.jl, src/inlineunion.jl
=> Object identity & no custom serialization to vector

src/data/writing_datatypes.jl
=> limit inlining

CHANGELOG.md, Project.toml, src/data/reconstructing_datatypes.jl, test/loadsave.jl
=> Fix union{}

src/data/custom_serialization.jl, test/loadsave.jl
=> add method for mutable custom serialization

CHANGELOG.md, Project.toml, src/data/reconstructing_datatypes.jl, test/Artifacts.toml, test/test_files.jl
=> unknown unionall type param

CHANGELOG.md, Project.toml, src/data/writing_datatypes.jl
=> remove usage of IOBuffer internals

CHANGELOG.md, Project.toml, src/datatypes.jl, test/loadsave.jl
=> avoid overflow in nfield loading

src/data/reconstructing_datatypes.jl, src/data/writing_datatypes.jl, test/loadsave.jl
=> Upgrading Singleton types and fix #571

CHANGELOG.md, Project.toml, src/data/writing_datatypes.jl, test/loadsave.jl
=> Fix error when trying to store instances of <: Function types

CHANGELOG.md, Project.toml, src/JLD2.jl, src/types.jl, test/loadsave.jl
=> v0.5.4 Hotfix for #603

.github/workflows/ci.yml, CHANGELOG.md, Project.toml, src/JLD2.jl, src/inlineunion.jl, test/inlineunion.jl
=> Version v0.5.9

docs/src/compression.md, filterpkgs/JLD2Bzip2/LICENSE.md
This PR makes the compression doc examples runnable and adds some more details on filter compatibility.
=> Compression doc fixes
