REQUIRE
src/JLD2.jl
src/datasets.jl
test/rw.jl

Ultimately we'd like to support more types of compression, add more tests, and perform the compression without constructing an intermediate buffer in memory, but this is a good start.
Fixes #5

Implement zlib compression

---

REQUIRE
appveyor.yml
benchmark/benchmark.jl
src/JLD2.jl
src/Lookup3.jl
src/attributes.jl
src/bufferedio.jl
src/data.jl
src/dataio.jl
src/datasets.jl
src/datatypes.jl
src/global_heaps.jl
src/groups.jl
src/misc.jl
src/mmapio.jl
src/superblock.jl
test/finalization.jl
test/internal.jl
test/rw.jl

Originally, I tried to build an `mmap`-free backend, but it was incredibly slow because I can't avoid allocating lots and lots of memory. So instead, I just got the existing `mmap` backend to work on Windows. I left around the `mmap`-free backend, because it works and it might be good to have someday.

Support Windows

---

test/rw.jl

these don't look necessary, and Compat isn't listed in REQUIRE or test/REQUIRE currently

drop usage of Compat

---

src/JLD2.jl
test/groups.jl

This PR implements `get()` and `get!()` for JLDFile and Group. Following the example from Base's `dict.jl`, it implements:
```
get(f::Union{JLDFile, Group}, name::AbstractString, default)
get!(f::Union{JLDFile, Group}, name::AbstractString, default)  # mutates f to add the given key
get(default_generator::Function, f::Union{JLDFile, Group}, name::AbstractString) # calls default_generator() to generate the default value if `name` not found
get!(default_generator::Function, f::Union{JLDFile, Group}, name::AbstractString)  # mutates f to add the given key created by calling `default_generator()` if `name` not found
```
This is somewhat suboptimal because it will perform the key lookup twice: once to check if the key is present and once to actually retrieve the element. Is that OK? This could …

add get() and get!() for JLDFile and Group

---

Project.toml

Use the assigned uuid, otherwise Pkg things they are two different packages.

Use the assigned uuid

---

src/data.jl
test/loadsave.jl

This patch changes usage of `setproperty!` to `setfield!` for mutable objects when `odr` is not `nothing`.
This should be considered a quick fix as probably a more consistent redesign of this function would be better, but I do not have access to appropriate test cases.
I have left comments in the code where probably things should be fixed, but I have left them as is for now not to introduce breaking changes I am not sure how to test against.

Patch for proper handling `DataFrame` objects

---

README.md

Currently, the Travis badge points to the wrong URL.
This pull request fixes the Travis badge.

Fix broken Travis badge in README.md

---

Project.toml
src/data.jl
test/internal.jl
test/modules-nested.jl

Fixes #154 
Fixes #112 
I found that in my Julia 1.0+ project: type names in a nested module (or even just `Core.String`) had duplicate module names in the path. e.g. `typname(A.B.C.T) = "A.B.C.C.T"` and also `typename(String) = "Core.Core.String"`.
This patch appears to solve that problem for Julia 1.0+ (and probably 0.7, but I suspect >0.6 needs testing) in my application. However the unit tests fail with:
```
┌ Info: read(
│   ms = Main.__anon__.MyStruct(2, [3.2, -1.7])
└   ) = ")"
┌ Warning: type Main.__anon__.MyStruct does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/Y5CVo/src/data.jl:1143
ERROR: LoadError: LoadError: For ms, read type getfield(JLD2.ReconstructedTypes, Symbol("##Main.__anon__.MyStruct#362")) does not agree with written type …
```

Bug fix: fix typename for nested modules

---

Project.toml
src/data.jl

In the good old days of JLD2 `0.1.2`, we only searched the `Main` module when trying to resolve a type. If we could not find the type in `Main`, we gave up.
In the subsequent bugfix releases of JLD2, we added code to make JLD2 work harder to find the type. However, when we made those changes, we did not preserve the order in which modules are searched. As a result, the latest release of JLD2 does not necessarily search the `Main` module first.
This pull request ensures that we always search the `Main` module first before searching other modules.
In my use case, I have a custom struct `Foo` which has a field of type `StatsModels.Schema`. My list of loaded modules in `Base.module_keys` includes `StatsModels`, `ScientificTypes`, and `Tables`.
It turns out that all three of those modules …

Always search the Main module first

---

Project.toml
src/stdlib.jl

There is a stdlib module named Future.
There is also a type Distributed.Future, and this type is exported.
This causes the bug https://github.com/JuliaIO/JLD2.jl/issues/165
This PR fixes the bug.
Fixes #165

Fix a bug that occurs because `Future` is a stdlib but also a type

---

src/dataio.jl
src/datasets.jl

Use the standard API—that's what it's for.

Avoid using the broken unsafe_isdefined function

---

src/data.jl

If you don't know what `Base.@pure` does, you're highly advised not to use it.

avoid marking some arbitrary functions pure

---

Project.toml
src/data.jl
test/A.jl
test/B.jl
test/modules.jl

Currently a non-deterministic bug is possible if two different modules have a type with the same name. `_resolve_type` drops the first path component (the top-level module) and instead searches all modules in hash order. This fixes it by just using the whole path. I believe this was introduced by 9ef1e0979b2b7b92e46a33d025b80bc4232bb611. If this looks good I'll add a test.

use full type path in type resolution

---

src/data.jl
src/datasets.jl
src/datatypes.jl
test/loadsave.jl

This fixes #125. 
Strings are converted to Vector{UInt8} for writing and reading. This makes sure that long strings are correctly handled as chunked or contiguous storage. The previous code always treated strings as compact storage, which fails when the size is larger than 2^16.

Corrected saving and loading of strings longer than 2^16 characters.

---

src/JLD2.jl

The current behavior is to silently accept the keyword.
```julia
import HDF5, JLD, JLD2
function writetest(f::Function, g::Function; kwargs...)
y = f("foo", "w"; kwargs...) do j
x = ones(Int,2)
j["x"] = x
@show x
x
end
f("foo", "r+"; kwargs...) do j
x = g(j["x"])
x[2] = 10 
@show x[:]
end
f("foo", "r"; kwargs...) do j
x = g(j["x"])
@show x[:]
if y == x
println("did NOT update")
else
println("did update")
end
end
end
function mmaptest()
println("HDF5")
writetest(HDF5.h5open, HDF5.readmmap)
println("JLD")
writetest(JLD.jldopen, x -> x; mmaparrays=true)
println("JLD2")
writetest(JLD2.jldopen, x -> x; mmaparrays=true)
end
```
And the result
```julia
julia> mmaptest()
HDF5
x = [1, 1]
x[:] = [1, 10]
x[:] = [1, 10]
did update
JLD
x = [1, 1]
x[:] = [1, 10]
x[:] = [1, 10]
did update
JLD2
x = [1, …
```

Add warning about using mmaparrays keyword

---

src/JLD2.jl
src/file_header.jl

This PR changes the (magic) header bytes to something that is less similar to what JLD uses.
Files with the old header will still be read but a commented out warning message has already been added.
This will become relevant when/if we make changes that break backwards compatibility.
Tests for this will fail since the tests rely on FileIO that does not recognize the new magic bytes yet.
closes #211

Magic Bytes

---

src/data.jl
test/loadsave.jl

When serializing immutable structs, `JLD2` attempts to generate an *in-line* representation for the given struct.
It does so by recursively trying to find the memory layout of all immutable fields.
This is neat for many applications but it fails when encountering recursive structs e.g.
```
struct RecursiveStruct
x::RecursiveStruct
RecursiveStruct() = new()
RecursiveStruct(x) = new(x)
end
```
This PR modifies the relevant function `hasfielddata` and `hasdata` to look for such recursive structs.
The functions now track which types they already have encountered and terminate the inlineing 
when a type signature is encountered again.
closes #189

Allow saving of 'recursive' immutable structs

---

.travis.yml
Project.toml
README.md
src/JLD2.jl
src/fileio.jl
src/loadsave.jl

I moved all FileIO-dependent function to a new file and wrapped it in an `@require`.
I left `loadtodict!` in `loadsave.jl` because it doesn't depend on FileIO, but it's not used outside the FileIO API, so we could also move it to the new file.
closes #204

Remove FileIO dependency

---

src/JLD2.jl
test/loadsave.jl

as discussed in #201.
Also ensures that only paths that either refer to a regular file or do not refer to any file system entity at all are passed to `openfile`. This prevents the weird error messages when trying to mmap directories (or even devices, although I haven't tried that yet).
I haven't made sure that the fallback option is accessible from all APIs yet, and I'm going to try to add a few tests as well.

Implement backend fallback behaviour

---

src/loadsave.jl

This makes the `@save` macro translate to something that does not have to compile an anonymous function every time.
Before: 
```julia
julia> @time @save "test.jld2" a
0.050988 seconds (7.13 k allocations: 389.079 KiB)
```
After:
```julia
julia> @time @save "test.jld2" a
0.002866 seconds (85 allocations: 8.531 KiB)
```

Make macro use try catch finally instead of do syntax

---

src/JLD2.jl
src/datasets.jl
src/mmapio.jl
src/stdlib.jl

This PR aims to make reading and writing independent files on multiple threads possible
by removing unnecessary global states and protecting necessary ones with `ReentrantLock`s.
Somehow this should have tests..

Make read and write threadsafe

---

Project.toml
src/data.jl

This is a bug that must have been introduced while improving the moduley/type resolution.
With a simple one-line change we make sure that types do not accidentally
get wrapped in `UnknownType` twice.
closes #240 
and likely also resolves #190

Make sure to not wrap unknown type again

---

Project.toml
src/data.jl
test/loadsave.jl

When reworking `hasdata` in #196 I forgot that structs can have multiple fields with the same type and introduced a bug.
closes #247

Fix hasdata when types occur multiple times

---

src/bufferedio.jl
test/bufferedreader.jl
test/runtests.jl

I came across this bug when looking into why all dataset/group names only contained the first character of the name. It turned out that it was always just reading the number of bytes corresponding to the size of the type, not the request number of bytes.

Fixes a bug where read would just read up to sizeof(T)

---

Project.toml
README.md
src/data.jl
src/file_header.jl
test/customserialization.jl
test/loadsave.jl
test/runtests.jl

This is a (likely still wildly inefficient) attempt at making custom serialization possible in JLD2.
Currently the problem is that the functions that figure out the on disk representation and the associated types are `@generated` functions - namely `h5type`, `jlconvert`, and  `odr`
This works only if the methods for `JLD2.writeas` are defined prior to the `@generated` definition which restricts usage to within JLD2.
In this PR I redefine the above three function definitions to regular functions.
At this point this seems to slow down things significantly. (That is also no surprise as these functions are called very often inside the code - sometimes unnecessarily so - since they were expected to be fast)
Whether this can be sped up to a point where this additional feature becomes an …

Make custom serialization possible

---

src/backwards_compatibility.jl
src/datasets.jl

This solves #269 and supercedes #270 by fixing a bug introduced in #152  .
When a scalar dataset such as a string exceeds `typemax(UInt16)` it no longer fits the
`CompactStorageMessage`. We now switch to `ContiguousStorageMessage` in that case.

use contiguousstoragemessage for large (scalar) data

---

Project.toml
src/data.jl
src/datatypes.jl

Currently `Bool`s are encoded as an opaque datatype which is different from what
HDF5.jl does and different from what seems logical.
Currently:
```
julia> jldopen("test2.jld2", "w") do f; f["b"] = true; f["false"]=false;end;
~> h5dump test2.jld2
HDF5 "test2.jld2" {
GROUP "/" {
GROUP "_types" {
DATATYPE "00000001" H5T_COMPOUND {
H5T_STRING {
STRSIZE H5T_VARIABLE;
STRPAD H5T_STR_NULLPAD;
CSET H5T_CSET_UTF8;
CTYPE H5T_C_S1;
} "name";
H5T_VLEN { H5T_REFERENCE { H5T_STD_REF_OBJECT }} "parameters";
}
ATTRIBUTE "julia_type" {
DATATYPE  "/_types/00000001"
DATASPACE  SCALAR
DATA {
(0): {
"Core.DataType",
()
}
}
}
DATATYPE "00000002" H5T_OPAQUE {
OPAQUE_TAG "";
};
ATTRIBUTE "julia_type" {
DATATYPE  "/_types/00000001"
DATASPACE  SCALAR
DATA {
(0): {
"Core.Bool",
()
}
}
}
}
DATASET "b" {
DATATYPE …
```

use standard h5 type for bools

---

Project.toml
docs/src/hdf5compat.md
src/data.jl
test/loadsave.jl
test/rw.jl

With this PR JLD2 will no longer error when attempting to store pointers.
Matching the behaviour of `Base.Serialization`, loaded pointers will always be null.
closes #251
also solves #128

Allow Pointers

---

src/data/reconstructing_datatypes.jl

Convert any type parameter that is `<: Union{Int64, Int32}` to the system's integer precision `Int`
prior to instantiating a parametric data type.
Adresses #281

WIP: Cross-platform (precision) type reconstruction

---

src/JLD2.jl
src/groups.jl

This PR changes the printing of `JLDFile`s in various ways
This is the normal case. The output is unchanged, but you can now optionally set the amount of lines displayed with an IOContext with the parameter `:jld2_numlines`. However, after implementing this feature, I already think that it shouldn't be added because it adds disproportionate amounts of weirdness. Also, the problem that I initially suggested this feature for is now solved more effectively (in my opinion) by the `printtoc` function (see below).
```
julia> f
JLDFile /home/lhupe/file.jld2 (read/write)
├─🔢 1
├─🔢 2
├─🔢 3
├─🔢 4
├─🔢 5
├─🔢 6
├─🔢 7
├─🔢 8
├─🔢 9
└─ ⋯ (8 more entries)
```
Also, the two-argument and three-argument `show` functions now behave differently
```
julia> [f, f]
2-element Array{JLD2.JLDFile{JLD2.MmapIO},1}: …
```

More printing

---

.github/workflows/ci.yml
src/backwards_compatibility.jl
src/data/reconstructing_datatypes.jl
src/data/writing_datatypes.jl

Use ismutabletype

---

Project.toml
src/backwards_compatibility.jl
src/data/reconstructing_datatypes.jl
src/data/writing_datatypes.jl
test/loadsave.jl

fix #327 DataType has no field ninitialized

---

src/JLD2.jl
src/precompile.jl

In order to reduce the "time-to-first-`jldopen`/`jldsave`" I added a `src/precompile.jl` file populated by SnoopCompile.
Before:
```jl
julia> @time using JLD2
0.839626 seconds (1.12 M allocations: 72.258 MiB, 2.57% gc time)
julia> @time jldsave("example.jld2"; a=1, b=2, c=[1.0,2.0], d=Dict(s => 2 for s in ["a", "b", "c"]))
6.407678 seconds (16.59 M allocations: 958.140 MiB, 7.07% gc time, 0.82% compilation time)
julia> @time jldopen("example.jld2") do _ end # fresh session
2.483562 seconds (7.79 M allocations: 451.146 MiB, 12.52% gc time)
```
After:
```jl
julia> @time using JLD2
0.997764 seconds (1.41 M allocations: 92.667 MiB, 2.02% gc time)
julia> @time jldsave("example.jld2"; a=1, b=2, c=[1.0,2.0], d=Dict(s => 2 for s in ["a", "b", "c"]))
4.672978 seconds (6.89 M allocations: 407.284 …
```

Add precompiles to reduce time to first `jldopen`/`jldsave`

---

src/JLD2.jl

On julia 1.5 this happens: #341 
Since `v1.5` is not officially supported, I will not spend the time to add optimization features to it.
referencing #340

Use precompile.jl only on most recent version

---

src/JLD2.jl
src/data/reconstructing_datatypes.jl
test/loadsave.jl
test/modules-nested.jl
test/runtests.jl

closes #354
This is a tricky thing but since it was already implemented, I'll just fix it for now.
Main idea: if the type of a struct field has changed, then JLD2 will check if there exists a `Base.convert(::Type{NewType}, oldtypeelement)` method. If there is, it will continue to reconstruct by calling `convert`.
This can however fail since e.g. `Base.convert(Float64, 3.14)` errors.
In that case, you end up with an annoying error that JLD2 cannot recover from. Only way out is to follow steps outlined in #242

Auto conversion of convertible types 

---

src/fileio.jl
test/loadsave.jl

This PR attempts to solve #358.
Since `String(k)` already works on symbols, I just added a warning when a key is a symbol.

Automatically transform symbol keys in strings with a warning

---

Project.toml
src/JLD2.jl

Just noticed that the definition of `OrderedDict` has been moved to `OrderedCollections.jl`. Switching out the dependency (away from `DataStructures.jl`)
improves load time `using JLD2` from ~0.5s to ~0.35s.

switch to OrderedCollections.jl

---

CHANGELOG.md
Project.toml
src/data/reconstructing_datatypes.jl
test/loadsave.jl

This changes the reconstruction of mutable structs to use `jl_set_nth_field` instead of `setfield!`.
The former does not appear to check the `const` property.
Since we are only just creating the struct and no other place has access to it, yet, this should be fine.
closes #410

const fields in mutable structs

---

CHANGELOG.md
Project.toml
docs/src/advanced.md
docs/src/customserialization.md
src/JLD2.jl
src/data/reconstructing_datatypes.jl
src/datasets.jl
test/loadsave.jl

This PR implements an experimental way of upgrading stored structs to an updated version. Example:
```julia
julia> struct A
x::Int
y::Float64
end
julia> save_object("test.jld2", A(1,2.0))
julia> load_object("test.jld2")
A(1, 2.0)
julia> struct A2
x::Float64
y::Float64
z::Float64 # x*y
end
julia> JLD2.rconvert(::Type{A2}, nt::NamedTuple) = A2(Float64(nt.x), nt.y, nt.x*nt.y)
julia> JLD2.load("test.jld2", "single_stored_object"; typemap=Dict("Main.A" => JLD2.Upgrade(A2)))
A2(1.0, 2.0, 2.0)
```
API is clumsy but it was rather easy to implement and could potentially be powerful for some applications.
Please test and give feedback if you're interested.

struct upgrade pathway

---

src/compression.jl

If you try to load a compressed file during precompilation (like top-level of your module, or in a `SnoopPrecompile.@precompile_all_calls`), the `@eval` s were causing an error since you're evaling into another module which is not allowed. You can just `getproperty` directly I think, works for my case, will wait for full suite of tests below to see if there's not some edge case.

allow loading compressed files during precompilation

---

src/datatypes.jl

time datatype is deprecated and broken according to https://docs.h5py.org/en/stable/special.html#storing-other-types-as-opaque-data
Closes #465

deprecate time datatype

---

src/data/reconstructing_datatypes.jl

previously it tried to to do
`Upgrade(NewStruct){OldStructparams....}`

Can't upgrade parametric types

---

CHANGELOG.md
src/backwards_compatibility.jl
src/data/reconstructing_datatypes.jl
src/data/type_defs.jl
src/data/writing_datatypes.jl
src/datasets.jl
src/metadataview.jl
test/isreconstructed.jl

eval-free reconstructed types

---

src/JLD2.jl
test/test_files.jl

Fixes https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/1292

Don't keep file in open files cache if it fails to read metadata

---

src/data/writing_datatypes.jl
test/loadsave.jl

fix roundtrip of Tuple{Type{Int}}

---

src/data/custom_serialization.jl
src/data/specialcased_types.jl

Reverts JuliaIO/JLD2.jl#492
Re #497 
Should likely have a patch release or alternative fix.

Revert "Align writeas for Dict with wconvert"

---

src/data/specialcased_types.jl

I think, this change should do it - i.e. expand the `writeas` applicability for `IdDict`s.
The change below that is mostly just a cleanup.

fix iddicts

---

src/JLD2.jl
src/loadsave.jl
src/precompile.jl

Ensure win7 can be precompiled
Win7 and below systems use IOStream method to ensure pre-compilation correct.

compat: no MmapIO for windows 7

---

src/data/specialcased_types.jl

module reference serialization

---

CHANGELOG.md
Project.toml
src/data/specialcased_types.jl
src/data/writing_datatypes.jl
test/loadsave.jl
test/test_files.jl

fix vararg tuples

---

src/data/reconstructing_datatypes.jl
test/Artifacts.toml
test/test_files.jl

fix reconstruction with unknown type param

---

src/compression.jl
src/data/custom_serialization.jl
src/data/specialcased_types.jl
src/data/writing_datatypes.jl
src/dataio.jl
src/datasets.jl
src/inlineunion.jl
src/julia_compat.jl
src/loadsave.jl
src/precompile.jl
test/loadsave.jl

This improves time to first execution in particular when handling many types.
Resolves the ancient issue #2 (this is where the test code below is from)
JLD2 v0.4.41
```
_       _ _(_)_     |  Documentation: https://docs.julialang.org
(_)     | (_) (_)    |
_ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 1.10.0 (2023-12-25)
_/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |
julia> include("jldtest.jl")
Precompiling JLD2
1 dependency successfully precompiled in 18 seconds. 10 already precompiled.
1.474348 seconds (2.41 M allocations: 157.608 MiB, 13.24% gc time, 99.76% compilation time)
0.213206 seconds (358.63 k allocations: 23.462 MiB, 3.82% gc time, 99.71% compilation time) …
```

Add @nospecializeinfer around worst offenders

---

src/data/reconstructing_datatypes.jl

Small and unimportant fix:
Added a missing word "in" to a warning message.

Add missing word in warning message

---

.gitignore
Project.toml
src/fileio.jl
src/loadsave.jl

This PR removes some rethrows which cause the real exception to be hidden (which makes using JLD2 more difficult
because I don't know the real reason an exception happened).

Don't hide exception data during loading and saving

---

.gitignore
docs/Project.toml
docs/make.jl
docs/src/advanced.md
docs/src/compression.md
docs/src/hdf5compat.md
docs/src/index.md
docs/src/legacy.md
src/JLD2.jl
src/attributes.jl
src/data/reconstructing_datatypes.jl
src/dataio.jl
src/datasets.jl
src/groups.jl
src/inlineunion.jl
src/loadsave.jl
src/misc.jl
src/mmapio.jl

- Fix markdown usage
- Make code examples more easy to read
- Use Documenter v1 for building

Update documentation site and docstrings

---

src/JLD2.jl
src/data/writing_datatypes.jl
test/loadsave.jl

Set `JLD2.DISABLE_COMMIT[] = true` to throw errors instead of committing types to files.
Can be used to guarantee *plain* files.

experimental disable commit

---

src/JLD2.jl
src/data/reconstructing_datatypes.jl
test/test_files.jl

Tries to turn committed types into `NamedTuple` and (non-committed) parametric type signatures into `Any`. 
```
julia> load("struct_reconstruction.jld2"; plain=true)
Dict{String, Any} with 4 entries:
"dms" => @NamedTuple{kvvec}((Any[@NamedTuple{first::String, second}(("a", (a = 1,)))],))
"tms" => @NamedTuple{1::Int64, 2}((1, (a = 1,)))
"s"   => (a = 1,)
"ds"  => @NamedTuple{kvvec}((Any[(first = "a", second = (a = 1,))],))
```

Draft: experimental plain reconstruction

---

src/data/reconstructing_datatypes.jl
src/datasets.jl
src/datatypes.jl
src/explicit_datasets.jl
src/macros_utils.jl
test/dataset_api.jl

Implements a dataset wrapper `ArrayDataset` that allows typestable slicing and update of array datasets using the `getindex` and `setindex!` API.

Draft: Slicing

---

src/committed_datatype_introspection.jl
src/data/reconstructing_datatypes.jl
src/data/writing_datatypes.jl
src/datalayouts.jl
src/datasets.jl
src/datatypes.jl
src/explicit_datasets.jl
src/file_header.jl
test/loadsave.jl

closes #36 
closes #175 
closes #401

new type encoding

---

src/data/reconstructing_datatypes.jl

remove warning that is no longer relevant

---

CHANGELOG.md
Project.toml
src/data/writing_datatypes.jl
test/loadsave.jl

fix #611 new version 0.5.7

---

CHANGELOG.md
Project.toml
src/data/reconstructing_datatypes.jl
src/io/dataio.jl
test/modules.jl

Nightlyfix

---

CHANGELOG.md
Project.toml
src/compression.jl
src/data/number_types.jl
src/data/reconstructing_datatypes.jl
src/data/specialcased_types.jl
test/loadsave.jl
test/modules.jl
test/runtests.jl

- switch to using loaded_modules_array

Draft: new version

---

src/Lookup3.jl
test/lookup3.jl

This PR uses the `bitrotate` function added in Julia v1.5, it also changes a `convert(UInt32, n)` to `n%UInt32` when setting the initial state to match what happens in the C code. Lastly, it adds a missing `GC.@preserve` around where a pointer to an array is used.

Cleanup of Lookup3 hash

---

CHANGELOG.md
Project.toml
src/data/reconstructing_datatypes.jl
test/loadsave.jl

Fixes https://github.com/JuliaIO/JLD2.jl/issues/628
It's a bit of a guess, but tests pass for me locally, including the test added here, which reproduces the issue on master for mutable structs.
On master
```
Error encountered while load File{DataFormat{:JLD2}, String}("a.jld2").
Fatal error:
mutable: Error During Test at /Users/ian/Documents/GitHub/JLD2.jl/test/loadsave.jl:750
Got exception outside of a @test
TypeError: in Union, expected Type, got a value of type JLD2.Upgrade
Stacktrace:
[1] jlconvert(::JLD2.MappedRepr{Union, JLD2.OnDiskRepresentation{(0, 16, 32), Tuple{String, Vector{Any}, Vector{Any}}, Tuple{JLD2.Vlen{String}, JLD2.Vlen{JLD2.RelOffset}, JLD2.Vlen{JLD2.RelOffset}}, 48}}, f::JLD2.JLDFile{JLD2.MmapIO}, ptr::Ptr{Nothing}, header_offset::JLD2.RelOffset)
@ JLD2 …
```

Fix unions for upgrades on mutable structs

---

CHANGELOG.md
Project.toml
src/compression.jl
src/data/reconstructing_datatypes.jl
src/data/specialcased_types.jl
test/modules.jl
test/runtests.jl

A large number of packages seems to be stuck on JLD2 0.4 and they error on upcoming 1.12 with 
```
[0KERROR: LoadError: UndefVarError: `module_keys` not defined in `Base`
[0KStacktrace:
[0K  [1] getproperty
[0K    @ ./Base_compiler.jl:47 [inlined]
```
so I think it is a good idea to fix things on 0.4 as well. To make the tests pass I also had to backport the loading decompressor deprecation.

Backports some fixes to 0.4

---

CHANGELOG.md
Project.toml
src/data/specialcased_types.jl
src/datasets.jl
src/dataspaces.jl
src/io/dataio.jl
test/loadsave.jl
test/runtests.jl

Implements the required special handling of `Memory` and `MemoryRef`.
Memory is treated as a regular mutable object and hence, object identity is preserved.
(e.g. when doing
```
m = Memory{Int}(undef, 10)
mr = memoryref(m, 1)
jldsave("test.jld2"; m, mr)
d = load("test.jld2")
d["m"] === d["mr"].mem
```
However potential aliasing between `Array` and `Memory` objects is ignored.

support for Memory and MemoryRef

---

CHANGELOG.md
src/data/writing_datatypes.jl
src/explicit_datasets.jl
test/Artifacts.toml
test/test_files.jl

This PR improves the `readmmap` function.
It will now figure out the byte alignment and fall back to mmapping `UInt8` and returning a `ReinterpretedArray` when direct mmapping is not possible.
closes #648

improved readmmap

---

Project.toml
filterpkgs/JLD2Bzip2/Project.toml
filterpkgs/JLD2Lz4/Project.toml

This version has no changes; it was to mark the API as stable.

Bump compat for ChunkCodec packages to v1

---

filterpkgs/JLD2Lz4/src/JLD2Lz4.jl

This is more of a comment because this error cannot be triggered on any existing hardware.
Ref #659

JLD2Lz4: Add check for LZ4 Frame magic during encoding

---

src/Filters.jl
src/datasets.jl

This PR changes the mutating function `set_local!(filter, odr, dataspace, datasetcreationprops)` to the non-mutating
`set_local(filter, odr, dataspace, datasetcreationprops)` and also makes `Shuffle` a `struct` instead of a `mutable struct`.
This is not a breaking change because `set_local!` is not used by any plugins yet, and currently, the internal filter interface is still experimental.
I imagine people will create global variables with filter options like:
```
const filters = [Shuffle(), Deflate()]
```
And then reuse this in multiple threads. With the current `set_local!` function for `Shuffle`, this would be a race condition.
This PR fixes that issue.

Avoid mutating filters.
